export const trades = [
    {
        name:"trade1",
        class:"col-6",
        label:"trade1",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade2",
        class:"col-6",
        label:"trade2",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade3",
        class:"col-6",
        label:"trade3",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade4",
        class:"col-6",
        label:"trade4",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade5",
        class:"col-6",
        label:"trade5",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade6",
        class:"col-6",
        label:"trade6",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade7",
        class:"col-6",
        label:"trade7",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    },
    {
        name:"trade8",
        class:"col-6",
        label:"trade8",
        options:[
            {
                label:"caca1",
                value:"1"
            },
            {
                label:"caca2",
                value:"2"
            },
            {
                label:"caca3",
                value:"3"
            },
            {
                label:"caca4",
                value:"4"
            },
            {
                label:"caca5",
                value:"5"
            }
        ]
    }
];